### ISSUE TITLE
People put personal mobile number as --mobileDevice paramter

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit-frontend#21]
See for example:
* https://farm.youzim.it/pipeline/291b501401491233e596c006/debug
* ...

As a consequence the scraper dies. We could help avoid this by:
* Directly checking in JS the input values
* Provide a link to the strings supported by Puppeters

**Comment by kelson42** [comment]
Zimit log:
```
[DEBUG] Confirming output is writable using /output/tmpur2f0sgw
[DEBUG] Title: FFMPEG Trac Wiki
[DEBUG] Language: eng
[DEBUG] Favicon: https://trac.ffmpeg.org/chrome/common/trac.ico
[DEBUG] Found 1373 records in WARCs
No such file or directory
Traceback (most recent call last):
  File "/usr/bin/zimit", line 333, in <module>
    zimit()
  File "/usr/bin/zimit", line 265, in zimit
    return warc2zim(warc2zim_args)
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 768, in warc2zim
    return warc2zim.run()
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 439, in run
    with Creator(
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 133, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/libzim/writer.py", line 162, in __init__
    self._creatorWrapper = _Creator(str(filename), main_page, index_language, min_chunk_size)
  File "libzim/wrapper.pyx", line 176, in libzim.wrapper.Creator.__cinit__
RuntimeError: Cannot create file /output/Trac FFMPEG Wiki 2021/1 _5180c451.zim.tmp
Exception ignored in: <function Creator.__del__ at 0x7f01b748e310>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/libzim/writer.py", line 178, in __del__
    if not self._closed:
AttributeError: 'Creator' object has no attribute '_closed'
```

See more at https://farm.youzim.it/pipeline/01816031a7d2fa9c2b0a8006/debug

**Comment by sahussain5599** [comment]
Hi. So in this issue the users should write their device name but they're instead putting their mobile numbers?

**Comment by kelson42** [comment]
@sahussain5599 yes, a basic misunderstanding of the option

**Comment by kelson42** [comment]
A selectbox with the list of available option is probably the best approach.

**Comment by rgaudin** [comment]
Fixed in zimfarm https://github.com/openzim/zimfarm/commit/8513539a2f9d18f39ec67900f99b94d5a6f0b0fd
To be deployed soon
